/**
 * Fake-account risk scoring.
 *
 * Used by the OTP controller to flag suspect vendor signups. Pure function:
 * given the channel + address, returns a { score, reasons[] } object the
 * signup controller can persist into `vendors.risk_score` /
 * `vendors.risk_reasons`. Heuristics are deliberately lightweight — the
 * goal is to surface likely-abuse cases for manual admin review, not to
 * auto-ban anyone.
 *
 * Signals scored:
 *   +30  email from a known disposable domain
 *   +20  email username looks auto-generated (long random string, no vowels)
 *   +20  phone uses a non-Nigerian prefix when the rest of the app is
 *        Nigerian-focused
 *   +10  email has no dots in the local-part (a@b vs a.b@c — soft signal)
 *   +10  phone number repeats the same digit 6+ times
 *
 * Anything >= 50 is considered "suspicious" and is flagged for review.
 * The admin dashboard surfaces flagged rows alongside verification_status.
 */

const DISPOSABLE_DOMAINS = new Set([
    'mailinator.com',
    'tempmail.com',
    '10minutemail.com',
    'guerrillamail.com',
    'trashmail.com',
    'yopmail.com',
    'throwawaymail.com',
    'fakeinbox.com',
    'getnada.com',
    'maildrop.cc',
    'discard.email',
    'sharklasers.com',
    'temp-mail.org',
]);

const SUSPICIOUS_THRESHOLD = 50;

function emailDomain(email) {
    const at = email.lastIndexOf('@');
    return at === -1 ? '' : email.slice(at + 1).toLowerCase();
}

function emailLocal(email) {
    const at = email.lastIndexOf('@');
    return at === -1 ? '' : email.slice(0, at);
}

function isAutoGeneratedLocal(local) {
    // 12+ chars with 2 or fewer vowels and at least 3 digits — classic
    // random-string pattern (e.g. xq83hd92kdf1).
    if (local.length < 12) return false;
    const vowels = (local.match(/[aeiou]/gi) || []).length;
    const digits = (local.match(/\d/g) || []).length;
    return vowels <= 2 && digits >= 3;
}

function hasNoDotsInLocal(local) {
    return local.length > 0 && !local.includes('.');
}

function phoneHasRepeatRun(phone) {
    return /(\d)\1{5,}/.test(phone);
}

function isNigerianPhone(phone) {
    // +234 followed by 10 digits. We're a Nigerian campus product so any
    // non-NG phone is mildly suspicious.
    return /^\+234\d{10}$/.test(phone);
}

/**
 * Score a signup. Pure — does not touch the database.
 * @param {{channel: 'email'|'phone', value: string}} input
 * @returns {{score: number, reasons: string[], is_suspicious: boolean}}
 */
function scoreSignup({ channel, value }) {
    const reasons = [];
    let score = 0;

    if (channel === 'email') {
        const domain = emailDomain(value);
        const local = emailLocal(value);

        if (DISPOSABLE_DOMAINS.has(domain)) {
            score += 30;
            reasons.push(`disposable_email:${domain}`);
        }
        if (isAutoGeneratedLocal(local)) {
            score += 20;
            reasons.push('auto_generated_username');
        }
        if (hasNoDotsInLocal(local)) {
            score += 10;
            reasons.push('no_dotted_local_part');
        }
    } else {
        // phone
        if (!isNigerianPhone(value)) {
            score += 20;
            reasons.push(`non_nigerian_prefix:${value.slice(0, 4)}`);
        }
        if (phoneHasRepeatRun(value)) {
            score += 10;
            reasons.push('repeated_digits');
        }
    }

    return {
        score,
        reasons,
        is_suspicious: score >= SUSPICIOUS_THRESHOLD,
    };
}

/**
 * Persist risk signals onto an existing vendor row. Best-effort: a flag
 * write that fails must NOT block signup.
 */
async function flagIfSuspicious({ vendorId, channel, value, risk }) {
    if (!vendorId || !risk) return;
    if (!risk.is_suspicious) return;

    try {
        const supabase = require('../config/supabase');
        await supabase
            .from('vendors')
            .update({
                risk_score: risk.score,
                risk_reasons: risk.reasons,
                is_suspicious: true,
                risk_checked_at: new Date().toISOString(),
            })
            .eq('id', vendorId);
    } catch (err) {
        // eslint-disable-next-line no-console
        console.warn('[risk] failed to persist flag', err?.message);
    }
}

module.exports = {
    scoreSignup,
    flagIfSuspicious,
    SUSPICIOUS_THRESHOLD,
};
